version: '3.9'
services:
  db:
    image: mariadb
    volumes:
    - openfire-db:/var/lib/mysql
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
    environment:
      MYSQL_ROOT_PASSWORD: openfire
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: openfire
      MYSQL_USER: openfire
      MYSQL_PASSWORD: openfire
    networks:
    - openfire
  app:
    depends_on:
    - db
    image: dramos777/openfire:1.0
    volumes:
    - openfire-arq:/opt/openfire
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.8"
          memory: 800M
      restart_policy:
        condition: on-failure
    ports:
    - "5222:5222"
    - "5269:5269"
    - "7443:7443"
    - "9090:9090"
    - "9091:9091"
    networks:
    - openfire
networks:
  openfire:
volumes:
  openfire-db:
  openfire-arq:
